name: Trigger auto deployment for container-app-s2v5gastx3wxi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-s2v5gastx3wxi-AutoDeployTrigger-579e19b7-d00d-4111-afd1-7594c53aaa20.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPS2V5GASTX3WXI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPS2V5GASTX3WXI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPS2V5GASTX3WXI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPS2V5GASTX3WXI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPS2V5GASTX3WXI_REGISTRY_PASSWORD }}
          containerAppName: container-app-s2v5gastx3wxi
          resourceGroup: todospaceaad4
          imageToBuild: default/container-app-s2v5gastx3wxi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


